actions:
  black:
    run: black --check {files}
    fix: black {files}
    include: "*.py"
    exclude:
      - .venv/
      - kinto/plugins/admin/node_modules/

  isort:
    run: isort --recursive --check-only .isort.cfg {files}
    fix: isort {files}
    include: "*.py"
    exclude:
      - .venv/
      - kinto/plugins/admin/node_modules/

  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude:
      - .venv/
      - kinto/plugins/admin/node_modules/
